version: '3.8'
services:  
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest    
    container_name: zurg
    restart: unless-stopped
    ports:
      - "127.0.0.1:9999:9999"
    volumes:
      - ./config.yml:/app/config.yml
      - zurgdata:/app/data

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    network_mode: "service:zurg"
    volumes:
      - ./rclone-config:/config/rclone
      - /mnt/zurg:/data:shared
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    command: "mount zurg: /data --allow-other --allow-non-empty --vfs-cache-mode full -vv --log-file /dev/stdout"

    depends_on:
      - zurg
    healthcheck:
      test: ["CMD", "ls", "/data/shows"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ./jellyfin-config:/config
      - /mnt/zurg:/data:ro
    depends_on:
      - rclone

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm-data:/data
      - ./npm-data/letsencrypt:/etc/letsencrypt

  
volumes:
  zurgdata:
